services:
  mongodb-fm:
    image: mongo:7.0.5
    container_name: financial-management_mongodb
    restart: unless-stopped
    volumes:
      - ./db:/data/db
  api-financial-management:
    build: ./server-node
    container_name: financial-management_api
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb-fm:27017/financial-management
    depends_on:
      - mongodb-fm
    restart: unless-stopped
  app-financial-management:
    build: ./client
    container_name: financial-management_app
    ports:
      - "4200:4200"
    environment:
      - NEXT_PUBLIC_API_URL=/api/financial-release
      - INTERNAL_API_URL=http://api-financial-management:3000
    depends_on:
      - api-financial-management
    restart: unless-stopped
